stages:
  - build

build:
  stage: build

  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]

  script:
    - mkdir -p /kaniko/.docker
    - |
      python3 - <<'PY'
      import json
      import base64
      import os

      with open(os.environ["CI_REGISTRY_KEY"], "r") as f:
          key = f.read()

      auth = base64.b64encode(
          ("json_key:" + key).encode()
      ).decode()

      config = {
          "auths": {
              "cr.yandex": {
                  "auth": auth
              }
          }
      }

      with open("/kaniko/.docker/config.json", "w") as f:
          json.dump(config, f)
      PY
    - /kaniko/executor
      --force
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "cr.yandex/crpbigo0qo703tmevafa/telegram-bot-for-ice-cream-shop:${CI_COMMIT_SHORT_SHA}"