stages:
  - build
  - deploy

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]

  script:
    - mkdir -p /kaniko/.docker
    - AUTH=$(printf 'json_key:%s' "$(cat "$CI_REGISTRY_KEY")" | base64 | tr -d '\n')
    - echo "{\"auths\":{\"cr.yandex\":{\"auth\":\"$AUTH\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --force
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "cr.yandex/crpbigo0qo703tmevafa/telegram-bot-for-ice-cream-shop:${CI_COMMIT_SHORT_SHA}"

deploy:
  image: mirror.gcr.io/ubuntu
  stage: deploy

  variables:
    ADMIN_INTERFACE_PORT: $ADMIN_INTERFACE_PORT
    ADMIN_LOGIN: $ADMIN_LOGIN
    ADMIN_PASSWORD: $ADMIN_PASSWORD

    POSTGRES_DB: $POSTGRES_DB
    POSTGRES_SERVICE: $POSTGRES_SERVICE
    POSTGRES_PORT: $POSTGRES_PORT
    POSTGRES_USER: $POSTGRES_USER
    POSTGRES_PASSWORD: $POSTGRES_PASSWORD

    TELEGRAM_API_KEY: $TELEGRAM_API_KEY

  script:
    - apt-get update && apt-get install -y curl
    - curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
    - export PATH=${PATH}:/root/yandex-cloud/bin/
    - curl -sSL https://raw.githubusercontent.com/test-always-included/mo/master/mo -o mo
    - chmod +x mo
    - ./mo docker-compose.prod.yml.template > docker-compose.prod.yml
    - echo "$CI_REGISTRY_KEY" > key.json
    - yc config set service-account-key key.json
    - >
      yc compute instance create-with-container
      --name telegram-bot-vm
      --zone ru-central1-a
      --folder-id b1q0iab6da8hl26o9a33
      --public-ip=true
      --create-boot-disk size=30
      --service-account-name telegram-bot
      --docker-compose-file docker-compose.prod.yml
      || true
    - >
      yc compute instance update-container
      --name telegram-bot-vm
      --folder-id b1q0iab6da8hl26o9a33
      --docker-compose-file docker-compose.prod.yml