stages:
    -build
build:
  stage: build
  # using kaniko to create a container inside the container for enhanced security.
  image:
    name: gcr.io/kaniko-project/executor:v1.6.8-debug
    entrypoint: [""]
  script:
    - nkdir -p /kanoko/ .docker
    # Pushing the container imageto the registry. The image is markedwith the commit hash.
    - echo "{\"auths\":{\"$CI_REGISTRY}" | base64 |tr -d'\n' )\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --force
      --context "${CI_PROJECT_IR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY}/S{CI_project_path}:${CI_COMMIT_SHORT_SHA}"